version: "3"
services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8080:3000"
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:latest
    container_name: database
    restart: always
    env_file:
      - .env
